import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState,useEffect } from 'react';
import Link from 'next/link'

const defaultEndpoint = "https://rickandmortyapi.com/api/character/";

export async function getServerSideProps() {  //function we use to fetch data

  const res = await fetch(defaultEndpoint)  //request to our endpoint
  const data = await res.json(); //method to grab output in JSON format
  return{
    props: {
      data //object as a prop
    }
  }

}

export default function Home({data}) {

  const {info,results: defaultResult = []} = data; //destrcuturing our results array from data obj
  const [results, updateResults] = useState(defaultResult);
  const [page, updatePage] = useState({
    ...info,
    current: defaultEndpoint
  });

  const {current} = page;

  useEffect(() => {
    if ( current === defaultEndpoint ) return;
  
    async function request() {
      const res = await fetch(current)
      const nextData = await res.json();
  
      updatePage({
        current,
        ...nextData.info
      });
  
      if ( !nextData.info?.prev ) {
        updateResults(nextData.results);
        return;
      }
  
      updateResults(prev => {
        return [
          ...prev,
          ...nextData.results
        ]
      });
    }
  
    request();
  }, [current]);


function handleLoad() {
  updatePage(prev => {
    return{
      ...prev,
      current: page?.next
    }
  });
}

function onSubmitHandler(e) {
  e.preventDefault(); //no refresh after form submit

  const { currentTarget = {}} = e;
  const fields = Array.from(currentTarget?.elements);
  const fieldQuery = fields.find(field => field.name === 'query');//find query from fields

  const value = fieldQuery.value || '';
  const endpoint = `https://rickandmortyapi.com/api/character/?name=${value}`; //new endpoint

  updatePage({
    current: endpoint
  });



}




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my Rick and Morty API Page.
        </h1>

        <p className={styles.description}>
          Get started by clicking on any character card!
        </p>

        <form className={styles.search} onSubmit={onSubmitHandler}>

          <input name="query" type="serach"/>
          <button>Serach</button>

          </form>

        <ul className={styles.grid}>
          {results.map(result => {  //method to create new list elem for each result
            const {id,name,image} = result; //grabbing id and name using id as a key (and image too)
            return (
          
          <li className={styles.card}>
            <Link href = "/characters/[id]" as={`/characters/${id}`}>
            <a>
              <img className={styles.img} src={image} alt={`${name} Thumbnail`}/>
              <h3>{name}</h3> 
            </a>
            </Link>
          </li>
          )})}
        </ul>
        <p className={styles.search}>
          <button onClick={handleLoad}>Load more</button>
        </p>


      </main>

      
    </div>
  )
  
}
